# Java-Exception-Handling
try-catch-finally
The try block contains a block of program statements within which an exception might occur. 
A catch block must be associated with a try block. The corresponding catch block executes if an exception of a particular type occurs within the try block. 
